server:
#   port: ${PORT}
  error:
    include-message: always

spring:
  application:
    name: fbk-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# spring.config.import: optional:configserver:${CONFIG_SERVER_URL}
spring.cloud.config.enabled: false
spring.cloud.config.discovery.enabled: false
# spring.cloud.discovery.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERER_URL}/eureka/
