server:
  port: ${PORT}

spring:
  application:
    name: fbk-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

spring.config.import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERER_URL}/eureka/

jwt:
  secret: ${JWT_SECRET}
